#
# This file contains configuration flags to customize a website
#

# Name of your site
site_name: NiftyHedgehog

# Short bio or description (displayed in the header)
description: A personal webpage to document my projects, thoughts, and experiences.

# Author details
author:
  name: Hieu Minh Nguyen
  email: hieu@niftyhedgehog.com
  github: cheehieu
  linkedin: hieuminh
  facebook: 
  twitter:  
  instagram: 
  flickr: 
  pinterest: 
  rss:
  stackoverflow:
  
# Disqus shortname, to enable commenting on posts
disqus: niftyhedgehogblog

# Google Analytics web tracking code, to activate tracking
google_analytics: UA-56490050-1

# Website
url: http://niftyhedgehog.com

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]	
